## simulx(model = NULL, parameter = NULL, output = NULL, treatment = NULL, regressor = NULL, varlevel = NULL, group = NULL, data = NULL, project = NULL, nrep = 1, npop = NULL, fim = NULL,result.folder = NULL, result.file = NULL, stat.f = "statmlx",  settings = NULL)
## simulx(model='myPKmodel.txt', ... )
## p <- c(a=1, b=-0.5, c=3)
## simulx(...,parameter=p, ... )
## o1 <- list(name=c('V','Cl'))
## o2 <- list(name='C',time=seq(0,24,by=0.1))
## simulx(..., output=list(o1, o2), ... )
## tr <- list(time=c(0,12), amount=50, tinf=1)
## simulx(...,treatment=tr, ... )
## reg <- list(name='x', time=c(0,2,5), value=c(5,10,7))
## simulx(..., regressor=reg, ... )
## g <- list(size=100, level='individual'))
## simulx(...,group=g, ... )
## simulx(..., project='monolix/pk_project.mlxtran', ... )
## simulx(..., settings=list(seed=s, digits=3), ... )
